
name: Install and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install_and_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        docker: ['debian', 'ubuntu', 'fedora']
        version: ['release-5.0-stable']
        root: ['/var/www/html/bugzilla/']

    container: ${{ matrix.docker }}

    steps:
      - if: ${{ contains(fromJson('["ubuntu", "debian"]'), matrix.docker) }}
        name: Install Bugzilla depencencies
        run: apt -y update && DEBIAN_FRONTEND=noninteractive apt -y install 
               apache2
               git
               build-essential
               mariadb-server
               libcgi-pm-perl
               libdigest-sha-perl
               libtimedate-perl
               libdatetime-perl
               libdatetime-timezone-perl
               libdbi-perl
               libtemplate-perl
               libemail-address-perl
               libemail-sender-perl
               libemail-mime-perl
               liburi-perl
               liblist-moreutils-perl
               libmath-random-isaac-perl
               libjson-xs-perl
               libdbd-mysql-perl
               libgd-perl
               libchart-perl
               libtemplate-plugin-gd-perl
               libgd-text-perl
               libgd-graph-perl
               libmime-tools-perl
               libwww-perl
               libxml-twig-perl
               libnet-ldap-perl
               libauthen-sasl-perl
               libnet-smtp-ssl-perl
               libauthen-radius-perl
               libsoap-lite-perl
               libxmlrpc-lite-perl
               libjson-rpc-perl
               libtest-taint-perl
               libhtml-parser-perl
               libhtml-scrubber-perl
               libencode-perl
               libencode-detect-perl
               libemail-reply-perl
               libhtml-formattext-withlinks-perl
               libtheschwartz-perl
               libdaemon-generic-perl
               libapache2-mod-perl2
               libapache2-mod-perl2-dev
               libfile-mimeinfo-perl
               libio-stringy-perl
               libcache-memcached-perl
               libfile-copy-recursive-perl
               libfile-which-perl

      - if: ${{ contains(matrix.docker, 'fedora') }}
        name: Install Bugzilla depencencies
        run: dnf -y install
               httpd
               git
               mariadb-server
               mod_perl
               mod_perl-devel
               httpd-devel
               gd-devel
               mariadb-devel
               graphviz
               patchutils
               gcc
               'perl(Apache2::SizeLimit)'
               'perl(Authen::Radius)'
               'perl(Authen::SASL)'
               'perl(Cache::Memcached)'
               'perl(CGI)'
               'perl(Chart::Lines)'
               'perl(Daemon::Generic)'
               'perl(Date::Format)'
               'perl(DateTime)'
               'perl(DateTime::TimeZone)'
               'perl(DBI)'
               'perl(Digest::SHA)'
               'perl(Email::MIME)'
               'perl(Email::Reply)'
               'perl(Email::Sender)'
               'perl(Encode)'
               'perl(Encode::Detect)'
               'perl(File::Copy::Recursive)'
               'perl(File::MimeInfo::Magic)'
               'perl(File::Which)'
               'perl(GD)'
               'perl(GD::Graph)'
               'perl(GD::Text)'
               'perl(HTML::FormatText::WithLinks)'
               'perl(HTML::Parser)'
               'perl(HTML::Scrubber)'
               'perl(IO::Scalar)'
               'perl(JSON::RPC)'
               'perl(JSON::XS)'
               'perl(List::MoreUtils)'
               'perl(LWP::UserAgent)'
               'perl(Math::Random::ISAAC)'
               'perl(MIME::Parser)'
               'perl(mod_perl2)'
               'perl(Net::LDAP)'
               'perl(Net::SMTP::SSL)'
               'perl(PatchReader)'
               'perl(SOAP::Lite)'
               'perl(Template)'
               'perl(Template::Plugin::GD::Image)'
               'perl(Test::Taint)'
               'perl(TheSchwartz)'
               'perl(URI)'
               'perl(XMLRPC::Lite)'
               'perl(XML::Twig)'

      - if: ${{ matrix.version }}
        name: Install Apache config
        env:
          debian_CONFIG: /etc/apache2/sites-available/bugzilla.conf
          ubuntu_CONFIG: /etc/apache2/sites-available/bugzilla.conf
          fedora_CONFIG: /etc/httpd/conf/httpd.conf
        run: |
            cat << EOF >> $${{ matrix.docker }}_CONFIG
               <Directory /var/www/html/bugzilla>
                 AddHandler cgi-script .cgi
                 Options +ExecCGI +FollowSymLinks
                 DirectoryIndex index.cgi index.html
                 AllowOverride All
               </Directory>
            EOF

      - if: ${{ contains(fromJson('["ubuntu", "debian"]'), matrix.docker) }}
        name: Enable apache modules
        run: a2enmod cgi headers expires rewrite

      - if: ${{ contains(fromJson('["ubuntu", "debian"]'), matrix.docker) }}
        name: Add the bugzilla site
        run: a2ensite bugzilla

      - if: ${{ contains(fromJson('["ubuntu", "debian"]'), matrix.docker) }}
        name: Start and run Apache in the background
        run: apachectl start

      - if: ${{ contains(matrix.docker, 'fedora') }}
        name: Start and run Apache in the background
        run: httpd

      - if: ${{ contains(matrix.docker, 'fedora') }}
        name: Prepare the database
        run: su -c "mariadb-install-db --user=mysql --basedir=/usr --datadir=/var/lib/mysql && mariadbd-safe --port 3307 --skip-syslog &" -s /bin/sh mysql

      - if: ${{ contains(fromJson('["ubuntu", "debian"]'), matrix.docker) }}
        name: Prepare the database
        run: su -c "mariadbd-safe --port 3307 --skip-syslog &" -s /bin/sh root

      - name: Create bugs user with password
        run: |
          while( ! mysqladmin ping ); do sleep 1; date; done
          mysql -u root -e "GRANT ALL PRIVILEGES ON bugs.* TO bugs@localhost IDENTIFIED BY '4ab75f1f4874be5c'"

      - if: ${{ matrix.version }}
        name: Clone Bugzilla ${{ matrix.version }}
        run: ${{ format('git clone --branch {0} https://github.com/bugzilla/bugzilla {1}', matrix.version, matrix.root) }}

      - name: Create config
        run: cd ${{ matrix.root }} && ./checksetup.pl

      - name: Set db password
        run: ${{ format('sed -i "s/db_pass.*/db_pass=\"4ab75f1f4874be5c\";/g" {0}/localconfig', matrix.root) }}

      - if: ${{ contains(fromJson('["ubuntu", "debian"]'), matrix.docker) }}
        name: Set web server group config
        run: ${{ format('sed -i "s/webservergroup.*/webservergroup=\"www-data\";/g" {0}/localconfig', matrix.root) }}

      - if: ${{ contains(matrix.docker, 'fedora') }}
        name: Set web server group config
        run: ${{ format('sed -i "s/webservergroup.*/webservergroup=\"apache\";/g" {0}/localconfig', matrix.root) }}

      - name: Non interactive config setup
        run: |
            cat << EOF >> ${{ matrix.root }}.setup
            \$answer{'ADMIN_EMAIL'} = 'test@bugzilla.org';
            \$answer{'ADMIN_PASSWORD'} = 'test1234';
            \$answer{'ADMIN_REALNAME'} = 'Test McTestface';
            \$answer{'NO_PAUSE'} = 1
            EOF

      - name: Check config
        run: cd ${{ matrix.root }} && ./checksetup.pl .setup

      - name: Test server
        run: cd ${{ matrix.root }} && ./testserver.pl http://localhost/bugzilla
