
name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        docker: ['centos', 'fedora', 'debian', 'ubuntu']
        root: ['/var/www/html/bugzilla/']
        version: ['4.4', '5.0', '5.2', 'harmony']
        # The distributions below have their own bugzilla packages, so we test those without per version checks
        include:
          - docker: 'opensuse/tumbleweed'
            root: '/srv/www/bugzilla/'
          - docker: 'opensuse/leap'
            root: '/srv/www/bugzilla/'
          - docker: 'gentoo/portage'
            root: '/var/www/html/bugzilla/'

    container: ${{ matrix.docker }}

    steps:
      - if: ${{ (matrix.docker == 'ubuntu' || matrix.docker == 'debian') }}
        run: apt install -y 
               apache2
               mariadb-server
               libappconfig-perl
               libdate-calc-perl
               libtemplate-perl
               build-essential
               libdatetime-timezone-perl
               libdatetime-perl
               libemail-sender-perl
               libemail-mime-perl
               libemail-mime-modifier-perl
               libdbi-perl
               libdbd-mysql-perl
               libcgi-pm-perl
               libmath-random-isaac-perl
               libmath-random-isaac-xs-perl
               libapache2-mod-perl2
               libapache2-mod-perl2-dev
               libchart-perl
               libxml-perl
               libxml-twig-perl
               perlmagick
               libgd-graph-perl
               libtemplate-plugin-gd-perl
               libsoap-lite-perl
               libhtml-scrubber-perl
               libjson-rpc-perl
               libdaemon-generic-perl
               libtheschwartz-perl
               libtest-taint-perl
               libauthen-radius-perl
               libfile-slurp-perl
               libencode-detect-perl
               libmodule-build-perl
               libnet-ldap-perl
               libauthen-sasl-perl
               libtemplate-perl
               libfile-mimeinfo-perl
               libhtml-formattext-withlinks-perl
               libfile-which-perl
               libgd-dev
               libmysqlclient-dev
               libemail-address-perl
               lynx
               graphviz
               python3-sphinx
               rst2pdf               

      - if: ${{ (matrix.docker == 'centos' || matrix.docker == 'fedora') }}
        run: dnf -y install
               httpd
               mysql-server
               mod_perl
               mod_perl-devel
               httpd-devel
               gd-devel
               mysql-devel
               graphviz
               patchutils
               gcc
               'perl(Apache2::SizeLimit)'
               'perl(Authen::Radius)'
               'perl(Authen::SASL)'
               'perl(Cache::Memcached)'
               'perl(CGI)'
               'perl(Chart::Lines)'
               'perl(Daemon::Generic)'
               'perl(Date::Format)'
               'perl(DateTime)'
               'perl(DateTime::TimeZone)'
               'perl(DBI)'
               'perl(Digest::SHA)'
               'perl(Email::MIME)'
               'perl(Email::Reply)'
               'perl(Email::Sender)'
               'perl(Encode)'
               'perl(Encode::Detect)'
               'perl(File::MimeInfo::Magic)'
               'perl(GD)'
               'perl(GD::Graph)'
               'perl(GD::Text)'
               'perl(HTML::FormatText::WithLinks)'
               'perl(HTML::Parser)'
               'perl(HTML::Scrubber)'
               'perl(IO::Scalar)'
               'perl(JSON::RPC)'
               'perl(JSON::XS)'
               'perl(List::MoreUtils)'
               'perl(LWP::UserAgent)'
               'perl(Math::Random::ISAAC)'
               'perl(MIME::Parser)'
               'perl(mod_perl2)'
               'perl(Net::LDAP)'
               'perl(Net::SMTP::SSL)'
               'perl(PatchReader)'
               'perl(SOAP::Lite)'
               'perl(Template)'
               'perl(Template::Plugin::GD::Image)'
               'perl(Test::Taint)'
               'perl(TheSchwartz)'
               'perl(URI)'
               'perl(XMLRPC::Lite)'
               'perl(XML::Twig)'

      - if: ${{ startsWith(matrix.docker, 'gentoo')}}
        run: emerge -av bugzilla

      - if: ${{ startsWith(matrix.docker, 'opensuse') }}
        run: zypper -n install bugzilla bugzilla-apache
